version: '3.4'

services:
  easy-post-ia-frontend:
    image: easy-post-ia-frontend:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/easy-post-ia-frontend
      - node_modules:/easy-post-ia-frontend/node_modules
    stdin_open: true
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
volumes:
  node_modules:
